---
name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.23.x', '1.24.x', '1.25.x']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: '**/go.sum'

      - uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: "2025.1.1"
          install-go: false
          cache-key: ${{ matrix.go-version }}

      - name: Test
        run: ${{ startsWith(matrix.os,'windows') && '.ci/scripts/test.bat' || '.ci/scripts/test.sh' }}
        env:
          GO_VERSION: ${{ matrix.go-version }}

      - name: Store test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.go-version }}-${{ matrix.os }}
          path: build/junit*.xml
